config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :users, :only => [:show, :profile] do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :genre
  resources :jams do
  resources :comments
  end
  
  root 'pages#home'

  get "users/show"
  get "pages/musicians"
  get "pages/howitworks"
  get 'musicians' => 'pages#musicians', as: :musicians
  get 'howitworks' => 'pages#howitworks', as: :howitworks
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :jam
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :jams
end

app/models/jam.rb
class Jam < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	belongs_to :genre
	belongs_to :jam_skill
end

app/models/jam_skill.rb
class JamSkill < ActiveRecord::Base
	has_many :jams
	has_many :users
end

app/models/skill_level.rb
class SkillLevel < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  attr_accessor :login

  validates_uniqueness_of :username
  validates_presence_of :username
  validates :username, length: { in: 4..20 }
  
  require 'aws-sdk-v1'
  require 'aws-sdk'

  has_attached_file :avatar, styles: { medium: "250x250#", thumb: "100x100#" },
                    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => ['image/gif', 'image/jpeg', 'image/png', 'image/x-ms-bmp']

	def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  acts_as_followable
  acts_as_follower

  has_many :jams
  has_many :comments
  belongs_to :jam_skill

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || jams_path
  end

	protected

  def after_update_path_for(resource)
      user_path(resource)
    end

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :username << :name << :email << :password << :password_confirmation << :remember_me << :jam_skill_id
	  devise_parameter_sanitizer.for(:sign_in) << :login << :password << :remember_me
    devise_parameter_sanitizer.for(:account_update) << :username << :name << :email << :password << :password_confirmation << :avatar << :location << :bio << :styles << :jam_skill_id << :user_instruments << :main_instrument << :influences << :equipment
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@jam = Jam.find(params[:jam_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.jam_id = @jam.id

		if @comment.save
			redirect_to jam_path(@jam)
		else
			render 'new'
		end
	end

	def destroy
		@jam = Jam.find(params[:jam_id])
		@comment = @jam.comments.find(params[:id])
		@comment.destroy

		redirect_to jam_path(@jam)
	end
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController
	before_action :find_jam, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:genre].blank?
			@jams = Jam.all.order("created_at DESC").paginate(page: params[:page], per_page: 9)
		else
			@genre_id = Genre.find_by(name: params[:genre])
			@jams = Jam.where(genre: @genre_id).order("created_at DESC").paginate(page: params[:page], per_page: 9)
		end
	end

	def show
		@comments = Comment.where(jam_id: @jam).all.order("created_at DESC")
	end

	def new
		@jam = current_user.jams.build
	end

	def create
		@jam = current_user.jams.build(jam_params)

		if @jam.save
			redirect_to @jam
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @jam.update(jam_params)
			redirect_to @jam
		else
			render 'edit'
		end
	end

	def destroy
		@jam.destroy
		redirect_to jams_path
	end

	private

	def find_jam
		@jam = Jam.find(params[:id])
	end

	def jam_params
		params.require(:jam).permit(:title, :location, :date, :time, :number_of_musicians, :instrument_types, :genre_id, :jam_skill_id, :information )
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, except: [:home]
	def home	
	end

	def musicians
		@users = User.all.order("created_at DESC").paginate(page: params[:page], per_page: 20)
	end

	def howitworks
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.find(params[:id])
	end
	
	def follow
		@user = User.find(params[:id])
		if current_user
			if current_user === @user
				flash[:notice] = "You cannot follow yourself."
			else
		      current_user.follow(@user)
		      flash[:notice] = "You are now following #{@user.username}."
		  end	
		    redirect_to user_path
	    else
    		flash[:notice] = "You must login to follow other users"
  		end 
  end

  def unfollow
	  	@user = User.find(params[:id])

	  if current_user
	  	if current_user === @user
				flash[:notice] = "You cannot unfollow yourself."
			else
		    current_user.stop_following(@user)
		    flash[:notice] = "You are no longer following #{@user.username}."
		  end
		  redirect_to user_path
		  else
		    flash[:error] = "You must login to un-follow other users"
			end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jams_helper.rb
module JamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@jam, @jam.comments.build]) do |f|
	= f.input :content, label: "Reply to thread"
	%br/
	= f.button :submit, "Post Comment", class: "comment-button"

app/views/jams/_form.html.haml
= simple_form_for @jam do |f|
	= f.label "Choose a Genre"
	= f.collection_select :genre_id, Genre.all, :id, :name, { promt: "Choose a Genre"}
	= f.input :title, :placeholder =>  "90s Rock Jam Sessions"
	= f.input :location, label: "Preferred Location" , :placeholder => "Brooklyn, Manhattan, NYC, Sweatshop Studios..."
	= f.input :date, label: "Preferred Day/Days", :placeholder =>  "Wed & Thrus, Weekends, Any Day..."
	= f.input :time, label: "Time", :placeholder =>  "Daytime, 6-9 PM, All Day..."
	= f.input :number_of_musicians, label: "Number of Musicians", :placeholder =>  "1,2,3,4,5,6..."
	= f.input :instrument_types, label: "Instruments Wanted", :placeholder =>  "Drums, Guitar, Bass, Vocals, Banjo, DJ"
	= f.label "Preferred Skill Level"
	= f.collection_select :jam_skill_id, JamSkill.all, :id, :name, { promt: "Preferred Skill Level"}
	%br/
	%br/
	= f.input :information, label: "About the Jam"
	%br/
	%br/
	= f.button :submit

app/views/jams/edit.html.haml
.row.spacing.wrapper
	%h1 Edit Jam Session
	= link_to "Go back", @jam
.row.content-wrapper
	.small-6.large-centered.columns
		= render 'form'
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

		

app/views/jams/index.html.haml
.sub-header
	%h2 Find Jam Sessions in NYC.
	.genre-filter-box
		%h3{"data-dropdown" => "drop2", "aria-controls" => "drop2", "aria-expanded" => "false"}
			= link_to "Select Genre", jams_path, class:'genre-filter'
			= link_to image_tag('/images/arrow_down_rounder_black.png')
			%h4#drop2.f-dropdown.genre-dropdown{"data-dropdown-content" => "true", "aria-hidden" => "true"} 
				%li= link_to "All Genres", jams_path, class: 'genre-tags'
				- Genre.all.each do |genre|
					%li= link_to genre.name, jams_path(genre: genre.name), class: 'genre-tags'

.row.spacing.content-wrapper
	%h2.title 
		LATEST JAMS
	- if params[:genre].blank?
		%p All Genres
	- else
		%p 
			Genre:
			= @genre_id.name
	- @jams.each do |jam|
		.results-box
			%h4.text= link_to jam.title, jam
			%p.genre
				= jam.genre.name
			%p
				= image_tag jam.user.avatar.url(:thumb), class: "index-profile-pic"
				%br/
				by 
				= link_to jam.user.username, user_path(jam.user.id)
			
			%p.info
				=image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/9868-200.png", width: "35px")
				Where >
				= jam.location
				%br/ 
				=image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/173848-200.png", width: "35px")
				When >
				= jam.date
				%br/
				=image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/11910-200.png", width: "35px")
				Members Wanted >
				= jam.number_of_musicians
				%br/
				=image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/91427-200.png", width: "35px")
				Comments > 
				= jam.comments.count

			%h5.jam_skill
				- if jam.jam_skill.name == "Beginner"
					Level:
					= image_tag('/images/rock_hand_small.png', width: "15px")
					= image_tag('/images/rock_hand_grey.png', width: "15px")
					= image_tag('/images/rock_hand_grey.png', width: "15px")
				- if jam.jam_skill.name == "Intermediate"
					Level:
					= image_tag('/images/rock_hand_small.png', width: "15px")
					= image_tag('/images/rock_hand_small.png', width: "15px")
					= image_tag('/images/rock_hand_grey.png', width: "15px")
				- if jam.jam_skill.name == "Advanced"
					Level:
					= image_tag('/images/rock_hand_small.png', width: "15px")
					= image_tag('/images/rock_hand_small.png', width: "15px")
					= image_tag('/images/rock_hand_small.png', width: "15px")
			= link_to 'Check it Out', jam, class: 'button'
	.clearfix
	%br/			
	= will_paginate @jams, previous_label: "Newer", next_label: "Older", inner_window: 1, outer_window: 0
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path
	
	

app/views/jams/new.html.haml
.row.spacing.wrapper
	%h1.title Create Jam Session!
.row.content-wrapper
	.small-6.large-centered.columns
		= render 'form'
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

app/views/jams/show.html.haml
.row.wrapper
	.spacing
	= link_to "← Back", jams_path
%br/
.row
	.small-6.large-5.columns
		.jam-info-box
			.modify-box
				- if @jam.user == current_user
					= link_to " Edit", edit_jam_path(@jam), class: "edit-jam"
					%span /
					= link_to " Delete", jam_path(@jam), class: "delete-jam", method: :delete, data: { confirm: "Are you sure?" }
			.clearfix
			%h1= @jam.title
			.small-6.large-5.columns
				= link_to image_tag(@jam.user.avatar.url(:medium), class: "profile-pic" ), user_path(@jam.user.id)
			.small-6.large-7.columns	
				%h6
					Jam Leader: 
				%h6
					= link_to @jam.user.username, user_path(@jam.user.id), class: "jam-username"
				%h6= @jam.user.main_instrument
			.clearfix
			%hr/
			.row
				%h3.jam-skill
					- if @jam.jam_skill.name == "Beginner"
						Level:
						= image_tag('/images/rock_hand.png', width: "20px")
						= image_tag('/images/rock_hand_white.png', width: "20px")
						= image_tag('/images/rock_hand_white.png', width: "20px")
						%span{"data-tooltip" => "true", "aria-haspopup" => "true", "class" => "has-tip", "title" =>  "Beginner: No need to know a lot, maybe some covers and just be familiar with the notes. "} ?
					- if @jam.jam_skill.name == "Intermediate"
						Level:
						= image_tag('/images/rock_hand.png', width: "20px")
						= image_tag('/images/rock_hand.png', width: "20px")
						= image_tag('/images/rock_hand_white.png', width: "20px")
						%span{"data-tooltip" => "true", "aria-haspopup" => "true", "class" => "has-tip", "title" =>  "Intermediate: You must be able to keep up with chords, times, changes and overall improvization. Must know notes and/or times"} ?
					- if @jam.jam_skill.name == "Advanced"
						Level:
						= image_tag('/images/rock_hand.png', width: "20px")
						= image_tag('/images/rock_hand.png', width: "20px")
						= image_tag('/images/rock_hand.png', width: "20px")
						%span{"data-tooltip" => "true", "aria-haspopup" => "true", "class" => "has-tip", "title" =>  "Advanced: Must know your instrument by heart. Must know all music vocabulary and be able to play a wide range of styles."} ?
				%br/
				.large-6.columns
					%p.jam-elements
						Genre:
				.large-6.columns
					%p.jam-elements
						= @jam.genre.name
				.large-6.columns
					%p.jam-elements
						Location: 
				.large-6.columns
					%p.jam-elements
						= @jam.location
				.large-6.columns
					%p.jam-elements
						Preferred Days:
				.large-6.columns
					%p.jam-elements
						= @jam.date
				.large-6.columns 
					%p.jam-elements
						Preferred Time: 
				.large-6.columns 
					%p.jam-elements
						= @jam.time
				.large-6.columns
					%p.jam-elements
						Musicians Wanted:
				.large-6.columns
					%p.jam-elements
						= @jam.number_of_musicians
				.clearfix
				.large-6.columns
					%p.jam-elements
						I Need:
				.large-6.columns
					%p.jam-elements
						= @jam.instrument_types

				.clearfix
				%p.jam-elements
					Description:
					%br/
					= @jam.information

	.small-6.large-7.columns.comments-box	
		%h4 Start the Conversation
		%br/
		- if user_signed_in?
			= render "comments/form"
		- else
			%h5 
				You need to 
				= link_to "login", new_user_session_path
				to post comments.	
		%p.comment-count= pluralize(@jam.comments.count, "Comment")
		#comments
			- @comments.each do |comment|
				.comment
					.userbox
						= link_to image_tag(comment.user.avatar.url(:thumb), class: 'mini-avatar' ), user_path(comment.user.id)
						.username
							= link_to comment.user.name, user_path(comment.user.id)
							.comment-delete 
								- if comment.user == current_user
									= link_to "X", [comment.jam, comment], method: :delete, data: { confirm: "Are you sure?" }
						.comment-date
							= time_ago_in_words(comment.created_at)
							ago.
						
					.content
						= comment.content		
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title JamSesh - Find other musicians to jam with in NYC
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= javascript_include_tag 'vendor/modernizr'
	%meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
	= favicon_link_tag 'favicon.ico'
	%link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "//brick.a.ssl.fastly.net/TeX+Gyre+Heros:400,700"}
	= csrf_meta_tags
	/.   __                      _        _                         .
	/.  / _| _ __   __ _  _ __  | | __   (_) _   _   __ _  _ __     .
	/. | |_ | '__| / _` || '_ \ | |/ /   | || | | | / _` || '_ \    .
	/. |  _|| |   | (_| || | | ||   <    | || |_| || (_| || | | | _ .
	/. |_|  |_|    \__,_||_| |_||_|\_\  _/ | \__,_| \__,_||_| |_|(_).
	/.                                 |__/                         .
	/  hello@frankjuan.com
.off-canvas-wrap{"data-offcanvas" => "true"}
	- if notice
		#notice-wrapper
			%p.notice= notice
	- elsif alert
		#notice-wrapper
			%p.alert= alert

	%header
		.row.header-wrapper
			= link_to "", jams_path, class: "logo"
			%nav
				- if user_signed_in?
					= link_to "Start a Jam", new_jam_path, class: "button"
					.nav-username
						%p{"data-dropdown" => "drop1", "aria-controls" => "drop1", "aria-expanded" => "false"}
							= link_to image_tag(current_user.avatar.url(:medium) , class: "header-profile-pic" ), user_path(current_user)
							= link_to image_tag('/images/nav_arrow_down.png', width: "10px"), user_path(current_user)
							/ = link_to current_user.name + " ↓", user_path(current_user.id), class:'nav-user'
							%ul#drop1.f-dropdown{"data-dropdown-content" => "true", "aria-hidden" => "true"} 
								%li 
									= link_to "Profile", user_path(current_user.id)
								%li 
									= link_to "Edit", edit_user_registration_path
								%li
									= link_to "Sign Out", destroy_user_session_path, method: :delete	
					.nav-menu
						= link_to "Jams", jams_path
						= link_to "Musicians", musicians_path
				- else
					.auth-links
						= link_to "Browse", jams_path
						= link_to "Log in", new_user_session_path
						= link_to "Join", new_user_registration_path, class: "button"			
				
				#{ link_to image_tag('/images/nav_icon.png', width: "40px"), '#', class: "right-off-canvas-toggle"}

	%main.inner-wrap			
		= yield
	
		%aside.right-off-canvas-menu
			%ul.off-canvas-list
				- if user_signed_in?
					%h5 
						=link_to image_tag(current_user.avatar.url(:medium) , class: "header-profile-pic" ), user_path(current_user)
						=link_to current_user.name, user_path(current_user)
					%li= link_to "Edit Profile", edit_user_registration_path
					%li= link_to "Start a Jam", new_jam_path
					%li= link_to "Jams", jams_path
					%li= link_to "Musicians", musicians_path		
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete	

				- else
					%li= link_to "Browse", jams_path
					%li= link_to "Log in", new_user_session_path
					%li= link_to "Join", new_user_registration_path		

app/views/pages/home.html.haml
.home-overlay
	.home-header
		.logo
	.welcome
		- if user_signed_in?
			.home-sign-out
				= link_to image_tag(current_user.avatar.url(:medium), class: "header-profile-pic" ), user_path(current_user)
				= link_to "Log Out", destroy_user_session_path, method: :delete
			%h1 
				Welcome Back, 
				%span= current_user.name
				%br/
				= link_to "Browse Jam", jams_path, class: "button"
				or
				= link_to "Create your Own", new_jam_path, class: "button"
		- else
			.home-menu-right
				= link_to "Log in", new_user_session_path
				= link_to "Sign up", new_user_registration_path, class: "signup-btn"	
			%h1
				Find Musicians to 
				%span Jam 
				With in Your City.
				%p A social network for musicians who just want to jam and experiment.
				= link_to "Browse Jams", jams_path, class: "button"
				%p
					Already have an account?
					= link_to "Login", new_user_session_path, class: "home-login"

	.how-it-works
		.row
			%h1 How it Works
			.small-2.large-4.columns
				= image_tag "/images/home_create_profile.png", width: "200px"
				%h4 1. Create Profile
				%p Share location, instruments, preferred styles and musical influences on your profile to let others know what you are all about.
			.small-4.large-4.columns
				= image_tag "/images/home_talk_to_musicians.png", width: "200px"
				%h4 2. Talk to Musicians
				%p Browse jam sessions and start connecting with other musicians. If you think you are a good fit, let them know you are interested.
			.small-6.large-4.columns
				= image_tag "/images/home_start_jammin.png", width: "200px"

				%h4 3. Start Jamming!
				%p After everybody agrees on a date and place, meet up and let your creative juices flow!
		.spacing

	.get-started
		%h1 
			Ready to Start Jamming?
			= link_to "Get Started", new_user_registration_path, class: "button"

		
	.footer-home
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

app/views/pages/howitworks.html.haml
.row.wrapper
	.spacing
		.row
			%h1 How it Works
			.small-2.large-4.columns
				= image_tag "https://d30y9cdsu7xlg0.cloudfront.net/png/108261-200.png"
				%h4 Create Profile
			.small-4.large-4.columns
				= image_tag "https://d30y9cdsu7xlg0.cloudfront.net/png/144340-200.png"
				%h4 Talk to Musicians
			.small-6.large-4.columns
				= image_tag "https://d30y9cdsu7xlg0.cloudfront.net/png/38990-200.png"
				%h4 Start Jammin'
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

app/views/pages/musicians.html.haml
.row.content-wrapper.spacing
	%h1.title ALL MUSICIANS
	- @users.each do |user|
		.small-block-grid-2.medium-block-grid-3.large-block-grid-4.musicians
			= link_to image_tag(user.avatar.url(:medium)), user_path(user.id), class: "profile-pic"
			%br/
			= link_to user.username, user_path(user.id)
			%br/
			= user.main_instrument
	.clearfix
	= will_paginate @users, previous_label: "Newer", next_label: "Older", inner_window: 1, outer_window: 0
%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path

app/views/users/show.html.haml
.profile-sub-header
	.row.user-profile-wrap
		.small-2.large-4.columns	
			= image_tag @user.avatar.url(:medium), class: "profile-pic"
		.small-4.large-4.columns
			%h2.title= @user.username
			%h5 
				= @user.main_instrument
				*
				= @user.location
			%h5.user-skill
				Skill Level: 
				%br/
				- if @user.jam_skill.name == "Beginner"
					= @user.jam_skill.name
					%br/
					= image_tag('/images/rock_hand_small.png', width: "40px")
					= image_tag('/images/rock_hand_grey.png', width: "40px")
					= image_tag('/images/rock_hand_grey.png', width: "40px")
					= @user.jam_skill.name
				- if @user.jam_skill.name == "Intermediate"
					= @user.jam_skill.name
					%br/
					= image_tag('/images/rock_hand_small.png', width: "40px")
					= image_tag('/images/rock_hand_small.png', width: "40px")
					= image_tag('/images/rock_hand_grey.png', width: "40px")
				- if @user.jam_skill.name == "Advanced"
					= @user.jam_skill.name
					%br/
					= image_tag('/images/rock_hand_small.png', width: "40px")
					= image_tag('/images/rock_hand_small.png', width: "40px")
					= image_tag('/images/rock_hand_small.png', width: "40px")
		.small-6.large-4.columns
			.follow-box
				%h5.following 
					= @user.following_by_type_count('User')
					%br/
					Following	
				%h5.followers 
					= @user.followers_by_type_count('User')	
					%br/
					Followers

			.clearfix
			- if user_signed_in?
				= link_to "Follow", follow_user_path(@user), class: 'follow-btn button'
				= link_to "Unfollow", unfollow_user_path(@user), class: 'follow-btn button'
.spacing
.row.spacing
	.small-6.large-5.columns	
		%p 
			Main Instrument:
			%br/
			= @user.main_instrument
		%p
			Other Instruments:
			%br/
			- if @user.user_instruments.blank?
				No other instruments.
			- else
				= @user.user_instruments
		%p
			Favorite Genres: 
			%br/
			- if @user.styles.blank?
				No favorite genres yet.	
			- else			
				= @user.styles
		%p
			Influences: 
			%br/
			- if @user.influences.blank?
				No influences yet.
			- else
				= @user.influences	
		%p
			Equipment: 
			%br/
			- if @user.equipment.blank?
				No equipment yet.
			- else
				= @user.equipment
				
	
		/ = @user.all_following.map(&:username).join(" / ")
	
		/ = @user.followers.map(&:name).join(" / ")
		/ %br/

		/ - if user_signed_in?
		/ 	= link_to "Follow", follow_user_path(@user), class: 'btn followButton'
		/ 	*
		/ 	= link_to "Unfollow", unfollow_user_path(@user), class: 'btn followButton'



	.small-6.large-7.columns
		- if @user == current_user
			%p.edit= link_to "Edit Profile", edit_user_registration_path
		.clearfix
		%h4.title
			About 
			%br/
		%p
			- if @user.bio.blank?
				No bio yet.
			- else
				= @user.bio

%footer
	.row.wrapper
		= link_to "", jams_path, class: "logo"
		%nav.breadcrumbs
			= link_to "About", root_path
			= link_to "Privacy Policy", root_path
			= link_to "Terms & Conditions", root_path
			= link_to "Contact", root_path